import { StateContext } from "@/context/stateContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
        <title>Shirt Crafters</title> 
      </head>
      <body>
        <StateContext>{children}</StateContext>
      </body>
    </html>
  );
}
