import { StateContext } from "@/context/stateContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateContext>{children}</StateContext>
      </body>
    </html>
  );
}
